markdown: kramdown
highlighter: rouge

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Josh Lloyd"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
