markdown: kramdown
highlighter: rouge
max_related_posts: 3
excerpt_separator: <!--more-->
url: https://nevercast.net
website_info:
  name: nevercast.net
  description: Josh Lloyd's Blog. Programmer, Student.
owner:
  name: Josh Lloyd
  email: j.nevercast@gmail.com
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      enable_comments: yes
      is_post: yes
      type: post
      layout: post
      author: "Josh Lloyd"
  -
    scope:
      path: ""
      type: pages
    values:
      is_page: yes
      type: page
      nav_order: 999
      layout: page
