markdown: kramdown
highlighter: rouge
max_related_posts: 3
excerpt_separator: <!--more-->
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      is_post: yes
      type: post
      layout: post
      author: "Josh Lloyd"
  -
    scope:
      path: ""
      type: pages
    values:
      is_page: yes
      type: page
      layout: page
